### ISSUE TITLE
Support for Debian stretch?

### ISSUE THREAD

**Issue by alexandernst** [gplessis/dotdeb-nginx#100]
Is support for Debian stretch coming or on the roadmap?

**Comment by myazaki** [comment]
Would be great to know if there is any plan for Nginx for Stretch, same as for PHP 7, or we should search alternative methods.

**Comment by RealKelsar** [comment]
Yes, would be really nice to know.

**Comment by aderumier** [comment]
+1

**Comment by rockyluke** [comment]
About PHP : https://www.dotdeb.org/2017/01/27/php-7-1-dotdeb/

**Comment by aderumier** [comment]
>>https://www.dotdeb.org/2017/01/27/php-7-1-dotdeb/

"other Dotdeb packages are unaffected by this decision and I’ll keep providing them for the current stable & oldstable distributions."

so I think we can expect nginx ?

**Comment by vincus** [comment]
Anyone has update on this ? We use dotdeb nginx on most of our servers and really missing them since upgraded to stretch
Thank you

**Comment by gplessis** [comment]
First of all, thanks for your patience.

Since
- Stretch already includes [Nginx 1.10](https://packages.debian.org/search?suite=stretch&keywords=nginx) with full HTTP2 support and most of modules that Dotdeb provides
- Stretch-backports provides [Nginx 1.13](https://packages.debian.org/search?suite=stretch-backports&keywords=nginx),

... I don't really have plans for Nginx on Stretch. Is there anything missing from the above packages?

**Comment by alexandernst** [comment]
@gplessis pagespeed

**Comment by RealKelsar** [comment]
@gplessis aio

**Comment by swordsman78** [comment]
@gplessis Auth LDAP

**Comment by rlanvin** [comment]
> Stretch. Is there anything missing from the above packages?

Push Stream

**Comment by alexandernst** [comment]
Any news on this?

**Comment by danger89** [comment]
Use https://deb.sury.org/ for Debian Stretch.

https://packages.sury.org/php/dists/stretch/

[Read more...](https://www.dotdeb.org/2017/01/27/php-7-1-dotdeb/)

**Comment by Reiner030** [comment]
Good that @danger89 ignored the mentioned requests for `pagespeed`, `aio`, `Auth LDAP` and doubled the answers of @gplessis  and @rockyluke with only some more details ^^ (sorry, couldn't resist to remark this).

To be complete also NGINX itselfs offers Open Source packages:
https://www.nginx.com/resources/admin-guide/installing-nginx-open-source/#prebuilt_debian

----

NGINX and Debian packages are compiled with module support.
But neither Debian nor NGINX repositories have the nice amount of modules included as DotDeb had on Jessie even the Debian `nginx-extras` package automatically installs all supplied `libnginx-mod-*` modules except `libnginx-mod-rtmp`. And NGINX offers only some basic ones in Open Source version:

```
# grep ^Package: /var/lib/apt/lists/nginx.org_packages_mainline_debian_dists_stretch_nginx_binary-amd64_Packages | uniq | grep -v dbg
Package: nginx
Package: nginx-module-geoip
Package: nginx-module-image-filter
Package: nginx-module-njs
Package: nginx-module-perl
Package: nginx-module-xslt
Package: nginx-nr-agent
```

Because there is no final answer given for the question/requests here an idea for a slim but helpful DotDeb support of additional NGINX functionality if not too complicated to setup/build:

**=> Is it possible to offer only the additional modules for NGINX versions for stretch / stretch-backports** which could be ideally also acceptable for several subversions like security updates of NGINX which didn't need the recompile of the module itself?

Didn't know much about NGINX compiles, but for Apache 1, 2, 2.2 and 2.4 it was/is working great... ;)

**Comment by gplessis** [comment]
Hi all,

sorry for the very late answer. I have no plan to maintain Nginx packages beyond Jessie. 

As mentioned above, builds from Nginx, Debian backports or even packages from deb.sury.org would help you to keep your Nginx servers up-to-date.

**Comment by azfarhashmi** [comment]
is anyone from above provide more_headers module for stretch?
